Homework 06
Otus-DevOps-2017-11/AndreyErmilov_infra pull request #2
Opened 2017-12-22 21:36 UTC by AndreyErmilov

2017-12-24 11:13 UTC, Nklya commented
Описание PR нужно заполнять. Хотя бы "Выполнено ДЗ №6"

<img width="726" alt="screen shot 2017-12-24 at 14 12 40" src="https://user-images.githubusercontent.com/26086394/34326030-8625387c-e8b4-11e7-9d68-809926ed1dfa.png">

2017-12-24 11:40 UTC, Nklya requested changes
Добрый день.

Андрей, скрипты деплоя похожи на настоящие. Но есть проблема в том, что нужно проверять приведенные команды, прежде чем отправлять на проверку.

Замечания оставил ниже по коду. 
После фиксов рассмотрю еще раз.

PR закрывать и создавать новый НЕ нужно. Фиксы вносятся коммитами в эту ветку.

2017-12-24 11:40 UTC, Nklya commented on README.md
> +gcloud compute instances create reddit-app \
Эта команда в текущем виде не работает из-за проблем стартап скрипта.
Ты сам проверял?

2017-12-24 11:40 UTC, Nklya commented on scripts/deploy.sh
> +cd /root
Если твои скрипты работают только под рутом, это нужно отдельно описать в ридми.

2017-12-24 11:40 UTC, Nklya commented on startup.sh
> +git clone git@github.com:Otus-DevOps-2017-11/AndreyErmilov_infra.git
Клонирование по ssh не работает из-за необходимости подтвердить `RSA key fingerprint`
Самое простое переделать на https.

2017-12-24 11:40 UTC, Nklya commented on startup.sh
> +sudo scripts/install_ruby.sh
Откуда здесь возьмутся скрипты, если ты клонируешь мастер бранч, в котором этого еще нет?

2017-12-24 11:40 UTC, Nklya commented on scripts/deploy.sh
> +#!/bin/bash
Скрипты нужно вынести в корень репозитория. В следующем дз они переедут в `config-scripts`

2017-12-24 11:40 UTC, Nklya commented on scripts/install_mongodb.sh
> +#!/bin/bash
Скрипты нужно вынести в корень репозитория. В следующем дз они переедут в `config-scripts`

2017-12-24 11:40 UTC, Nklya commented on scripts/install_ruby.sh
> +#!/bin/bash
Скрипты нужно вынести в корень репозитория. В следующем дз они переедут в `config-scripts`

2017-12-24 11:42 UTC, Nklya commented
Плюс, у тебя есть конфликт из-за обновленного в прошлом ДЗ fnkpnk_test_fnkpnk.ovpn.

2017-12-25 14:46 UTC, AndreyErmilov commented on README.md
> +gcloud compute instances create reddit-app \
Николай, добрый день!
Все правки посмотрел, они понятны. Спасибо!
Я не проверял работу кода и это, конечно, неправильно.
В следующий раз буду проверять.

2017-12-26 09:16 UTC, Nklya approved these changes
Добрый день.

Андрей, условия дз выполнены, подготовка и деплой теперь корректные.

2017-12-26 09:18 UTC, Nklya commented
Я смержил с мастером чтобы не было мерж конфликта.

2017-12-26 11:40 UTC, merged