Homework 07
Otus-DevOps-2017-11/AndreyErmilov_infra pull request #3
Opened 2018-01-11 19:01 UTC by AndreyErmilov

2018-01-13 18:48 UTC, Nklya requested changes
Описание PR нужно заполнять.
`+` закоммичен .DS_Store

2018-01-13 18:50 UTC, Nklya commented
Есть вопрос.
Как можно было прийти к такому вот дереву?

<img width="466" alt="screen shot 2018-01-13 at 21 47 51" src="https://user-images.githubusercontent.com/26086394/34909052-a0e1dcae-f8ab-11e7-82eb-ee470c89662c.png">

2018-01-14 10:46 UTC, AndreyErmilov commented
Николай, не знаю, как я сумел заплести ветки почти в косичку 🤦‍♂ и пока не могу понять, как в принципе их можно привести в нормальное состояние. Скажи, пожалуйста, что конкретно мне нужно сделать для того, чтобы сдать домашнюю работу?

2018-01-14 16:03 UTC, Nklya commented
Привет. Завтра посмотрю подробнее.

2018-01-15 18:02 UTC, Nklya requested changes
Добрый вечер.
Андрей, сейчас дифф стал намного лучше.

Замечания:
1. Все переменные, которые ты задаешь в variables.example.json, должны быть указаны в секции variables https://www.packer.io/docs/templates/user-variables.html
Это позволит задавать значения по умолчанию и не пихать все в variables.json

2. В .gitignore добавь variables.json

2018-01-15 18:44 UTC, AndreyErmilov commented
Николай, понял на счет секции variables, спасибо.
Обновил файлы.

2018-01-15 19:22 UTC, Nklya commented
Нет, я имел в виду, что нужно занести секцию variables в сам шаблон. 
Например вот так https://github.com/Otus-DevOps-2017-11/VARyumin_infra/pull/3/files#diff-21d672a9538f283c2dcdeb2902016cd6R1

2018-01-16 08:24 UTC, AndreyErmilov commented
Николай, надеюсь, что теперь я понял, что и зачем делаю с variables.
Добавил секцию в основной json файл и обозначил две переменные, как обязательные (null). Остался один вопрос – стоит ли теперь убрать из variables.json.example переменную machine_type, которая в основном файле имеет дефолтное значение?

2018-01-16 09:56 UTC, Nklya approved these changes
Добрый день.

Да, теперь все ок.

2018-01-16 09:59 UTC, Nklya commented
1. Да, если дефолтное значение есть, можно в принципе убрать его из variables.json.example.
2. Тебе стоит настроить твой редактор, чтобы он добавлял пустую строку в конце файла при сохранении. https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline
У тебя сейчас такого нет, и отображаются вот такие красные стрелочки.
<img width="201" alt="screen shot 2018-01-16 at 12 58 21" src="https://user-images.githubusercontent.com/26086394/34982961-08623d3e-fabd-11e7-83ef-e845707c89f6.png">

2018-01-16 10:16 UTC, AndreyErmilov commented
Николай, спасибо, настроил пустую строку.

2018-01-16 10:16 UTC, merged