Homework 08
Otus-DevOps-2017-11/AndreyErmilov_infra pull request #4
Opened 2018-01-13 09:48 UTC by AndreyErmilov

Домашняя работа 08

2018-01-13 19:07 UTC, Nklya requested changes
Добрый вечер.
Андрей, как я уже писал в PR к 7 заданию, тебе стоит разобраться с гитом и привести репозиторий в нормальное состояние.

Текущий дифф понять невозможно.
Например, с чего вдруг, в этом PR удаляются скрипты?

2018-01-24 22:03 UTC, Nklya requested changes
Андрей, смержил мастер в эту ветку, теперь диффы нормальные.
Заодно вычистил VPN конфиги, чтобы не мешались.

Добавь в README описание, что сделано.
Все остальное выглядит ок.

2018-01-25 09:27 UTC, AndreyErmilov commented
Николай, спасибо!

Добавил в README инструкцию, как запускать приложение.
Посмотри, пожалуйста.

2018-01-25 20:08 UTC, Nklya approved these changes
Да, теперь ок.

2018-01-26 06:33 UTC, merged