Terraform 2
Otus-DevOps-2017-11/AndreyErmilov_infra pull request #5
Opened 2018-01-26 17:39 UTC by AndreyErmilov

Домашняя работа 9.
К сожалению так и не справился с заданиями со звездочкой.
Еще буду разбираться.

2018-01-26 17:51 UTC, Nklya requested changes
Добрый вечер.

Андрей, в принципе почти все сделано неплохо.

1. Кривое форматирование в шаблонах пакера
2. terraform.tfvars.example не актуализированы
3. Ну и самое главное, не сделано задание с модулем из режистри, слайд 61-62

2018-01-26 17:51 UTC, Nklya commented on packer/app.json
> +{
Криво отформатирован

2018-01-26 17:51 UTC, Nklya commented on packer/db.json
> +{
Криво отформатирован

2018-01-26 17:51 UTC, Nklya commented on terraform/prod/terraform.tfvars.example
> +disk_image = "reddit-base"
У нас тут как бы добавились еще переменные.

2018-01-26 17:51 UTC, Nklya commented on terraform/stage/terraform.tfvars.example
> +project = "infra-193207"
У нас тут как бы добавились еще переменные

2018-01-27 09:50 UTC, AndreyErmilov commented
Николай, добрый день!
Внес изменения в .json файлы packer, добавил пропущенное задание со слайдов 61-62 и добавил backend gcp. 

Посмотри, пожалуйста.

2018-01-29 15:32 UTC, Nklya approved these changes
Да, теперь все хорошо 👍

2018-01-29 16:10 UTC, merged